networks:
  dev:
    driver: bridge

services:
  bw_beverages:
    image: docker.io/library/bwbeverages
    container_name: bwbeverages-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  bwbeverages_db:
    image: postgres:latest
    container_name: bwbeverages_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BWDbBeverages
    ports:
      - "5434:5432"
    restart: always
    networks:
      - dev

volumes:
  bwbeverages_data:
